### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by aredridel** [comment]
@grawk I don't have access to publish but I've put a 0.1.2 tagged in the repo if you'd do the honors.

**Comment by grawk** [comment]
Seems that I don't have rights either. I wonder if only @johnraber does..

**Comment by aredridel** [comment]
It's almost like [there needs to be some way to manage group permissions across an organization in npm](https://www.npmjs.com/org). (though it only works for scoped packages.)

**Pull request merged**
